-- REVISAR SI YA ESTA CREADO
INSERT INTO QUICKWIN_MDS.EXTERNAL_RESOURCE_GROUPS
(
  EXTERNAL_RESOURCE_GROUP_ID,
  DESCRIPTION
)
VALUES(
  (
    SELECT Nvl(Max(E.EXTERNAL_RESOURCE_GROUP_ID),0) + 1
    FROM EXTERNAL_RESOURCE_GROUPS E
  ),
  '[22385] eSIM QW Code - ConfirmOrder'
);

INSERT INTO QUICKWIN_MDS.EXTERNAL_RESOURCE_GROUPS
(
  EXTERNAL_RESOURCE_GROUP_ID,
  DESCRIPTION
)
VALUES(
  (
    SELECT Nvl(Max(E.EXTERNAL_RESOURCE_GROUP_ID),0) + 1
    FROM EXTERNAL_RESOURCE_GROUPS E
  ),
  '[22385] Grupo para Esim:updateEstadoPorICCID'
);