SELECT * FROM INVOKE T WHERE T.INVOKE_ID = '2342';
SELECT * FROM EXTERNAL_RESOURCE_GROUPS T WHERE T.EXTERNAL_RESOURCE_GROUP_ID = '453';
SELECT * FROM EXTERNAL_RESOURCES T WHERE T.EXTERNAL_RESOURCE_ID = '14194';
SELECT * FROM EXTERNAL_RESOURCE_COMPONENTS T WHERE T.EXTERNAL_RESOURCE_ID = '14194';
SELECT * FROM INVOKE_MAPPING T WHERE T.INVOKE_ID = '2342';
--SELECT * FROM INVOKE_MAPPING T WHERE T.INVOKE_ID = '2747';
SELECT * FROM INVOKE_RESPONSE_EVALUATION T WHERE T.INVOKE_ID = '2342';