SELECT * FROM CAMPAIGN T WHERE T.CAMPAIGN_ID = '100056';
SELECT * FROM CAMPAIGN_OFFERS T WHERE T.CAMPAIGN_ID = '100056';
SELECT * FROM BEHAVIOUR_OPERATION T WHERE T.BEHAVIOUR_ID = 580;
SELECT * FROM BEHAVIOUR_OPERATION T WHERE T.BEHAVIOUR_OPERATION_ID = '718';
SELECT * FROM BEHAVIOUR_OPER_STAGES T WHERE T.BEHAVIOUR_OPERATION_ID = '718';
SELECT * FROM PRODUCT_TYPES T WHERE T.PRODUCT_TYPE_ID = 'PRT_CLONE1_QW';



SELECT * FROM behaviour_oper_stages T WHERE T.BEHAVIOUR_OPERATION_ID = 718 order by t.order_by;
SELECT * FROM BEHAVIOUR_OPER_INVOKE T WHERE T.BEHAVIOUR_OPER_STAGE_ID = 3196 order by t.order_by;
SELECT * FROM BEHAVIOUR_OPER_INVOKE T WHERE T.BEHAVIOUR_OPER_STAGE_ID = 3399 order by t.order_by;